# Generated by Django 5.1 on 2024-08-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0004_rename_born_place_author_born_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(max_length=1000),
        ),
    ]
