# Generated by Django 5.1 on 2024-08-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0005_alter_author_born_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="born_location",
            field=models.CharField(max_length=100),
        ),
    ]
