# Generated by Django 5.1 on 2024-08-28 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0006_alter_author_born_location"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="author_oid",
            field=models.CharField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="quote",
            name="author",
            field=models.CharField(),
        ),
    ]
