# Generated by Django 5.1 on 2024-08-28 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0007_quote_author_oid_alter_quote_author"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Quote",
        ),
    ]
