# Generated by Django 5.1 on 2024-08-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0009_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pgquote",
            name="quote",
            field=models.CharField(unique=True),
        ),
    ]
