# Generated by Django 5.1 on 2024-08-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quoteapp", "0003_alter_author_born_date_alter_author_fullname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="author",
            old_name="born_place",
            new_name="born_location",
        ),
    ]
